version: '3'
services:
  MS-Users:
    build:
      context: ./MS-Users
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=production
    networks:
      - Network
    depends_on:
      - mongo-db

  MS-Products:
    build:
      context: ./MS-Products
    ports:
      - "8082:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=production
    networks:
      - Network
    depends_on:
      - mongo-db

  MS-Orders:
    build:
      context: ./MS-Orders
    ports:
      - "8083:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=production
    networks:
      - Network
    depends_on:
      - mongo-db

  MS-Transactions:
    build:
      context: ./MS-Transactions
    ports:
      - "8084:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=production
    networks:
      - Network
    depends_on:
      - mongo-db

  MS-App:
    build:
      context: ./MS-App
    ports:
      - "8085:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=production
    networks:
      - Network
    depends_on:
      - mongo-db
  mongo-db:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
